

 const products = [
    {
        id:0,
        img:"but8.jpg",
        name:"Aurelia",
        sernum:"123asd1",
        quantity:1,
        size:[36,37,38,39],
        price:230.00,
        category:"Botki",
        like:false
    },
    {
        id:1,
        img:"but9.jpg",
        name:"Martina",
        sernum:"123asd1",
        quantity:1,
        size:[36,37,38,39],
        price:400.00,
        category:"Sneakers",
        like:false
    },        
    {
        id:2,
        img:"but7.jpg",
        name:"Laura",
        sernum:"123asd1",
        quantity:1,
        size:[36,37,38,39],
        price:120.00,
        like:false
    },
    {
        id:3,
        img:"but6.jpg",
        name:"Amelia",
        sernum:"123asd1",
        quantity:1,
        size:[36,37,38,39],
        price:500.00,
        category:"Botki",
        like:false
    },        
    {
        id:4,
        img:"but7.jpg",
        name:"Laura",
        sernum:"123asd1",
        quantity:1,
        size:[36,37,38,39],
        price:120.00,
        like:false
    },
    {
        id:5,
        img:"but6.jpg",
        name:"Amelia",
        sernum:"123asd1",
        quantity:1,
        size:[36,37,38,39],
        price:500.00,
        category:"Botki",
        like:false
    }
 ]
 export default products